language: ruby
dist: xenial
cache: bundler

services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE test;'

matrix:
  include:
    - rvm: 2.3
    - rvm: 2.4
    - rvm: 2.5
    - rvm: 2.6
    - rvm: 2.7
    - rvm: 2.6
      env: COVERAGE=BriefSummary,Coveralls
    - rvm: ruby-head
    - rvm: truffleruby
    - rvm: jruby-head
      env: JRUBY_OPTS="--debug -X+O"
  allow_failures:
    - rvm: ruby-head
    - rvm: truffleruby
    - rvm: jruby-head
